from odoo import models


def create_insight_records(env, insights):
    """
    Convert insights generated by rules_engine.py
    into dayflow.ai.insight Odoo records.
    """

    Insight = env["dayflow.ai.insight"]

    created_records = []

    for insight in insights:

        employee = False

        employee_id = insight.get("employee_id")

        if employee_id:
            employee = env["hr.employee"].search(
                [("id", "=", employee_id)],
                limit=1
            )

        values = {
            "name": insight.get("title", "HR Insight"),
            "insight_type": insight.get("type"),
            "severity": insight.get("severity"),
            "message": insight.get("message"),
            "employee_id": employee.id if employee else False,
            "department": insight.get("department"),
            "status": "open",
            "source": "rules",
        }

        record = Insight.create(values)

        created_records.append(record)

    return created_records